# version: 1.0.0
# Name as it appears on the Actions tab of GitHub
# (for current repo; this get's ignored if called from another repo)
---
name: 'Validate Commit Title'

permissions:
  contents: read

# Controls when the workflow will run
on:
  pull_request:
    paths:
      - '.github/workflows/pr-controls.yml'
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  commit_title:
    name: Controls to Standardize Pull Requests
    permissions:
      contents: read
      pull-requests: write
      labels: write
    # yamllint disable-line rule:line-length
    uses: sassy-bulldog/.github/.github/workflows/pr-controls.yml@v0.3.1 # x-release-please-version
